[package]
name = "photo_server"
version = "0.2.0"
edition = "2021"

[dependencies]
afire = "1.1.0"
simple_config_parser = "1.0.0"

markdown = "0.3"
regex = "1.5.4"
lazy_static = "1.4.0"
mut_static = "5.0.0"
image = "0.23.14"
fast_image_resize = "2.2.0"
indicatif = "0.17.2"
